//! The protocol test vectors this crate owns (`testdata/vectors/v1/`,
//! `docs/spec/README.md#5`), generated by the independent Python
//! implementation in `scripts/vectors/`. Ed25519 is deterministic, so every
//! signature must match byte for byte; sealed boxes and name ciphertexts are
//! randomised, so those cases open fixed bytes.

use std::path::PathBuf;

use galata_vault::keys::vectors::run;
use galata_vault::proto::vectors::check_file;

fn check(construct: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/vectors/v1")
        .join(format!("{construct}.json"));
    let n = check_file(&path, run).unwrap_or_else(|e| panic!("{e}"));
    assert!(n > 0, "{construct} has no cases");
}

#[test]
fn keys() {
    check("keys");
}

#[test]
fn names() {
    check("names");
}

#[test]
fn descriptors() {
    check("descriptors");
}

#[test]
fn bundles() {
    check("bundles");
}

#[test]
fn records() {
    check("records");
}

#[test]
fn signatures() {
    check("signatures");
}

#[test]
fn children() {
    check("children");
}
