//! The protocol test vectors this crate owns (`testdata/vectors/v1/`,
//! `docs/spec/README.md#5`): strings, paths, the audit chain and proof of
//! work, generated by the independent Python implementation in
//! `scripts/vectors/` and run through this crate's code.

use std::path::PathBuf;

use galata_vault::proto::vectors::{check_file, run};

fn check(construct: &str) {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/vectors/v1")
        .join(format!("{construct}.json"));
    let n = check_file(&path, run).unwrap_or_else(|e| panic!("{e}"));
    assert!(n > 0, "{construct} has no cases");
}

#[test]
fn strings() {
    check("strings");
}

#[test]
fn paths() {
    check("paths");
}

#[test]
fn audit() {
    check("audit");
}

#[test]
fn pow() {
    check("pow");
}

/// The checker is not vacuous: a case whose expectation was edited fails,
/// naming the case.
#[test]
fn a_planted_disagreement_fails_naming_the_case() {
    let src =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../testdata/vectors/v1/strings.json");
    let mut doc: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(src).unwrap()).unwrap();
    let case = doc["cases"]
        .as_array_mut()
        .unwrap()
        .iter_mut()
        .find(|c| c["expect"] == "checksum_mismatch")
        .unwrap();
    case["expect"] = "success".into();
    case["outputs"] = serde_json::json!({ "key": "00" });
    let id = case["id"].as_str().unwrap().to_owned();
    let dir = std::env::temp_dir().join(format!("gv-vectors-plant-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let planted = dir.join("strings.json");
    std::fs::write(&planted, serde_json::to_string(&doc).unwrap()).unwrap();
    let err = check_file(&planted, run).unwrap_err();
    std::fs::remove_dir_all(&dir).unwrap();
    assert!(err.contains(&id), "{err}");
}
