"""Type stubs for the native module built from crates/gv-py."""

__version__: str
EXPIRY_WARNING_SECS: int

class NativeError(Exception):
    """args: (kind, code, message). Mapped to galata_vault's exceptions."""

class Vault:
    def __init__(self, token: str, server: str) -> None: ...
    @staticmethod
    def from_token_file(path: str, server: str) -> Vault: ...
    @property
    def scope(self) -> str: ...
    @property
    def vault_id(self) -> str: ...
    @property
    def last_expires_at(self) -> int | None: ...
    @property
    def token_expires_at(self) -> int | None: ...
    def get_bytes(self, name: str, version: int | None = None) -> bytes: ...
    def list(self) -> list[tuple[str, int, int, int]]: ...
    def set(self, name: str, value: bytes) -> int: ...
    def load_items(self, only: list[str] | None = None) -> list[tuple[str, bytes]]: ...
    def get_config(self, name: str, version: int | None = None) -> tuple[str, int, str, bytes]: ...
    def list_configs(self) -> list[tuple[str, int, int, int]]: ...
    def set_config(
        self,
        name: str,
        body: bytes,
        format: str,
        allow_literals: bool = False,
        expect_version: int | None = None,
        expect_absent: bool = False,
    ) -> int: ...
    def verify_audit(
        self, known: str | None = None
    ) -> tuple[str | None, tuple[int | None, int] | None]: ...

def run_cli(args: list[str]) -> int: ...
def _vectors_run(construct: str, case: str) -> str: ...
